services:
  mongo:
    image: mongo:latest
    container_name: mongo
    volumes:
      - mongo-data:/data/db
    ports:
      - "${MONGO_PORT}:${MONGO_PORT}"

  api:
    build:
      context: ./ApiServer
      dockerfile: Dockerfile.Api
    depends_on:
      - mongo
    env_file:
      - ./.env
    ports:
      - "${API_PORT}:${API_PORT}"
    volumes:
      - media_data:/usr/src/app/media

  recommend:
    build:
      context: ./RecommendServer
      dockerfile: Dockerfile.recommend
    env_file:
      - ./.env
    command: ["${RECOMMEND_PORT}"]
    volumes:
      - user_data:/usr/targil3/user_data

volumes:
  mongo-data: # mongo
  user_data: # recommender
  media_data: # api media